//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;AdventureWorks2017&quot;,
        ///  &quot;Collation&quot;: &quot;SQL_Latin1_General_CP1_CI_AS&quot;,
        ///  &quot;CollationCodePage&quot;: 1252,
        ///  &quot;CollationIgnoreCase&quot;: true,
        ///  &quot;Objects&quot;: [
        ///    {
        ///      &quot;ServerName&quot;: &quot;SampleServer&quot;,
        ///      &quot;DatabaseName&quot;: &quot;AdventureWorks2017&quot;,
        ///      &quot;SchemaName&quot;: &quot;dbo&quot;,
        ///      &quot;Name&quot;: &quot;AWBuildVersion&quot;,
        ///      &quot;ObjectID&quot;: 1125579048,
        ///      &quot;Type&quot;: 23
        ///    },
        ///    {
        ///      &quot;ServerName&quot;: &quot;SampleServer&quot;,
        ///      &quot;DatabaseName&quot;: &quot;AdventureWorks2017&quot;,
        ///      &quot;SchemaName&quot;: &quot;dbo&quot;,
        ///      &quot;Name&quot;: &quot;DatabaseLog [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventureWorks2017 {
            get {
                return ResourceManager.GetString("AdventureWorks2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[uspGetBillOfMaterials]
        ///    @StartProductID [int],
        ///    @CheckDate [datetime]
        ///AS
        ///BEGIN
        ///    SET NOCOUNT ON;
        ///
        ///    -- Use recursive query to generate a multi-level Bill of Material (i.e. all level 1 
        ///    -- components of a level 0 assembly, all level 2 components of a level 1 assembly)
        ///    -- The CheckDate eliminates any components that are no longer used in the product on this date.
        ///    WITH [BOM_cte]([ProductAssemblyID], [ComponentID], [ComponentDesc], [PerAssemblyQty], [Standa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_uspGetBillOfMaterials {
            get {
                return ResourceManager.GetString("dbo_uspGetBillOfMaterials", resourceCulture);
            }
        }
    }
}
